In [3]:
import numpy as np
list_ = ["1","2","3","4","5"]
array_list = np.array(object = list_)

In [4]:
# Viewing array_list
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [ ]:
'''Question-1'''

In [6]:
'''In Python, the names "list_" and "array_list" are not special, 
and the data type of a variable is determined by the type of object it refers to. 
If you have used these names for variables, it depends on how you have defined or assigned values to them.

However, in general terms, if you have created a standard Python list, it will have the data type list. 
If you are using an array from the array module in Python, it will have the data type array.array.'''

print('Data type of list_ is :',type(list_))
print('Data type of array_list is :',type(array_list))

Data type of list_ is : <class 'list'>
Data type of array_list is : <class 'array.array'>


In [ ]:
'''Question-2'''

In [7]:
for i in list_:
    print(f'Element value : {i}, datatype = {type(i)}')

Element value : 1, datatype = <class 'int'>
Element value : 2, datatype = <class 'int'>
Element value : 3, datatype = <class 'int'>
Element value : 4, datatype = <class 'int'>
Element value : 5, datatype = <class 'int'>


In [8]:
for i in array_list:
    print(f'Element value : {i}, datatype = {type(i)}')

Element value : 1, datatype = <class 'int'>
Element value : 2, datatype = <class 'int'>
Element value : 3, datatype = <class 'int'>
Element value : 4, datatype = <class 'int'>
Element value : 5, datatype = <class 'int'>


In [ ]:
'''Question-3'''

In [9]:
array_list = np.array(object = list_, dtype = int)

In [10]:
# Viewing array_list
array_list

array([1, 2, 3, 4, 5])

In [ ]:
'''In Python, both lists and arrays can contain elements of various data types. 
However, the specific data types of elements in a list or an array depend on the values you've assigned to them.'''

In [11]:
# Printing data types of each and every element in list_:
for i in list_:
    print(f'Element value : {i}, datatype = {type(i)}')

Element value : 1, datatype = <class 'int'>
Element value : 2, datatype = <class 'int'>
Element value : 3, datatype = <class 'int'>
Element value : 4, datatype = <class 'int'>
Element value : 5, datatype = <class 'int'>


In [12]:
# Printing data types of each and every element in modified array_list
for i in array_list:
    print(f'Element value : {i}, datatype = {type(i)}')

Element value : 1, datatype = <class 'numpy.int64'>
Element value : 2, datatype = <class 'numpy.int64'>
Element value : 3, datatype = <class 'numpy.int64'>
Element value : 4, datatype = <class 'numpy.int64'>
Element value : 5, datatype = <class 'numpy.int64'>


In [ ]:
'''Here is the Example'''

In [18]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
'''Question-4'''

In [16]:
# Showing num_array shape
num_array.shape

(2, 3)

In [17]:
# Showing num_array size
num_array.size

6

In [ ]:
'''Question-5'''

In [21]:
## Using np.zeros to create a 3X3 matrix containing zeros
array_5 = np.zeros((3,3))
array_5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# Verifying Matrix size and shape
print(f'Size of array_5 is {array_5.size}')
print(f'Shape of array_5 is {array_5.shape}')

Size of array_5 is 9
Shape of array_5 is (3, 3)


In [ ]:
'''Question-6'''

In [23]:
# Creating identity matrix using np.eye
array_6 = np.eye(5)
array_6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])